require('./runtime.cjs');
const {_electron:electron}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const path=require('node:path'),fs=require('node:fs'),assert=require('node:assert/strict');
const root=path.resolve('.'),profile=path.join(root,'tmp/advanced-profile'),out=path.join(root,'tmp/qa');fs.mkdirSync(out,{recursive:true});fs.rmSync(profile,{recursive:true,force:true});
const config={executablePath:require('./runtime.cjs').electronPath(),args:['--no-sandbox','--disable-gpu',path.join(root,'app'),'--user-data-dir='+profile],env:{...process.env,ELECTRON_DISABLE_SECURITY_WARNINGS:'true'}};
(async()=>{let app,page;const errors=[];try{
 app=await electron.launch(config);page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('h1');
 const go=async v=>page.locator(`.nav [data-view="${v}"]`).click();
 const field=async(k,v)=>{const el=page.locator(`[data-field="${k}"]`);await el.fill(String(v));await el.press('Tab')};
 const action=async a=>page.locator(`[data-action="${a}"]`).first().click();
 const addEntry=async name=>{await go('poderes');await action('catalog');await page.locator('#catalog-search').fill(name);await page.waitForFunction(n=>C.entries.some(e=>e.name===n),name);const id=await page.evaluate(n=>C.entries.find(e=>e.name===n).id,name);await page.locator(`[data-action="add-entry"][data-id="${id}"]`).click()};
 const saveItem=async()=>{await page.locator('#item-confirm').check();await action('save-item');await page.waitForFunction(()=>!document.querySelector('#modal').open)};
 await go('personagem');await field('name','Titã dos modificadores');
 for(const [k,v] of Object.entries({F:1500,H:3,R:2,A:2,PdF:4})){await page.locator(`[data-attr="${k}"]`).fill(String(v));await page.locator(`[data-attr="${k}"]`).press('Tab')}
 assert.equal(await page.evaluate(()=>ch().attrs.F),1500);assert.ok(await page.evaluate(()=>R.calculate(ch()).warnings.some(w=>w.includes('limite sugerido'))));
 await go('ajustes');await field('budget',200000);await field('modifiers.F',20000);await field('modifiers.fd',-12000);await page.locator('[data-field="ruleMode"]').selectOption('free');assert.deepEqual(await page.evaluate(()=>R.calculate(ch()).warnings),[]);
 await go('poderes');await action('custom');await page.locator('#item-name').fill('Espada monumental');await page.locator('#modal summary').filter({hasText:'Bônus permanentes'}).click();await page.locator('#effect-melee').fill('1500');await saveItem();assert.equal(await page.evaluate(()=>R.calculate(ch()).fa),23003);
 await go('modificadores');await action('new-bonus');await page.locator('#bonus-name').fill('Transformação suprema');await page.locator('#bonus-value').fill('50000');await page.locator('#bonus-target').selectOption('melee');await page.locator('#bonus-duration').selectOption('rounds');await page.locator('#bonus-rounds').fill('2');await action('save-bonus');assert.equal(await page.evaluate(()=>R.calculate(ch()).fa),73003);
 await action('next-round');assert.equal(await page.evaluate(()=>ch().bonuses[0].remaining),1);await action('next-round');assert.equal(await page.evaluate(()=>R.calculate(ch()).fa),23003);await action('undo');assert.equal(await page.evaluate(()=>ch().bonuses[0].enabled),true);await action('redo');assert.equal(await page.evaluate(()=>ch().bonuses[0].enabled),false);await action('undo');
 await page.screenshot({path:path.join(out,'modificadores.png'),fullPage:true});
 await action('delete-bonus');await action('confirm-delete-bonus');assert.equal(await page.evaluate(()=>ch().bonuses.length),0);await action('undo');assert.equal(await page.evaluate(()=>ch().bonuses[0].value),50000);
 // Canceling an edited option cannot mutate its saved choices.
 await addEntry('Energia Extra');await page.locator('#choice-version').selectOption({index:1});assert.equal(await page.locator('#item-cost').inputValue(),'2');await saveItem();
 await addEntry('Sentidos Especiais');await page.locator('#choice-version').selectOption({index:1});await saveItem();assert.equal(await page.evaluate(()=>ch().items.find(i=>i.name==='Sentidos Especiais').choices.senses.split(',').length),7);
 await addEntry('Ataque Especial');await page.locator('#choice-attack').selectOption('PdF');await page.locator('#choice-level').selectOption('2');await page.locator('[data-special="Perigoso"]').check();await page.locator('[data-special="Poderoso"]').check();assert.equal(await page.locator('#item-cost').inputValue(),'6');await saveItem();await action('list');const special=await page.evaluate(()=>ch().items.find(i=>i.name==='Ataque Especial').id);await page.locator(`[data-action="activate-item"][data-id="${special}"]`).click();assert.equal(await page.evaluate(()=>R.calculate(ch()).currentPM),4);await action('close');
 await addEntry('Arena');await page.locator('#choice-detail').fill('Ruínas ancestrais');await saveItem();await action('list');const arena=await page.evaluate(()=>ch().items.find(i=>i.name==='Arena').id);await page.locator(`[data-action="activate-item"][data-id="${arena}"]`).click();await page.locator(`[data-action="activate-item"][data-id="${arena}"]`).click();assert.equal(await page.evaluate(()=>ch().bonuses.filter(b=>b.name.startsWith('Arena:')).length),1);
 // High values survive sharing and file import; no invisible truncation.
 const exportedPath=path.join(out,'tita.3det.json');await app.evaluate(({dialog},p)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:p})},exportedPath);await action('export');await page.waitForTimeout(250);const exported=JSON.parse(fs.readFileSync(exportedPath,'utf8'));assert.equal(exported.version,2);assert.equal(exported.characters[0].modifiers.F,20000);assert.equal(exported.characters[0].items[0].effects.melee,1500);
 await app.evaluate(({dialog},p)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[p]})},exportedPath);await action('import');assert.equal(await page.evaluate(()=>state.characters.length),2);assert.equal(await page.evaluate(()=>ch().bonuses[0].value),50000);
 await go('sessao');await page.locator('[data-field="combat.opponentScale"]').selectOption('Sugoi');await page.locator('#damage-fa').fill('20');await page.locator('#damage-fd').fill('5');await action('calculate-damage');assert.match(await page.locator('#damage-result').innerText(),/150 PV/);await action('apply-damage');assert.equal(await page.evaluate(()=>R.calculate(ch()).currentPV),0);await action('undo');assert.equal(await page.evaluate(()=>R.calculate(ch()).currentPV),10);
 await page.locator('[data-action="condition"][data-condition="Paralisado"]').click();await page.locator('#roll-type').selectOption('defense');await action('roll');assert.match(await page.locator('#last-roll').innerText(),/Indefeso: sem dado/);await page.locator('#resource-amount').fill('1');await action('damage');assert.equal(await page.evaluate(()=>ch().conditions.includes('Paralisado')),false);
 await page.locator('#roll-mod').fill('20000');await action('roll');assert.equal(await page.locator('#roll-mod').inputValue(),'20000');
 await app.evaluate(({dialog},p)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:p})},path.join(out,'tita.pdf'));await action('pdf');await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('PDF salvo'));
 await go('historico');assert.ok((await page.locator('.content').innerText()).includes('Realizar rolagem'));await page.screenshot({path:path.join(out,'historico.png'),fullPage:true});
 await go('ajustes');await field('modifiers.F','99999999999999999999');assert.equal(await page.evaluate(()=>ch().modifiers.F),20000);assert.ok(await page.locator('[data-field="modifiers.F"]').evaluate(el=>!!el.validationMessage));await field('modifiers.F',20000);
 await go('personagem');await field('notes','Teste do histórico persistente');assert.equal(await page.locator('.topbar [data-action="undo"]').isEnabled(),true);await action('undo');assert.equal(await page.evaluate(()=>ch().notes),'');await page.evaluate(()=>flushSave());const selected=await page.evaluate(()=>ch().id);await app.close();app=null;
 app=await electron.launch(config);page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('h1');assert.equal(await page.evaluate(()=>ch().id),selected);assert.equal(await page.evaluate(()=>ch().attrs.F),1500);assert.equal(await page.evaluate(()=>ch().modifiers.F),20000);assert.equal(await page.evaluate(()=>ch().modifiers.fd),-12000);assert.equal(await page.evaluate(()=>ch().items[0].effects.melee),1500);assert.equal(await page.evaluate(()=>ch().bonuses[0].value),50000);await action('redo');assert.equal(await page.evaluate(()=>ch().notes),'Teste do histórico persistente');
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(960,720));await go('modificadores');await page.screenshot({path:path.join(out,'modificadores-compacto.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.deepEqual(errors,[]);console.log('PASS: valores altos e negativos; modo livre; modificadores com duração; desfazer/refazer persistente; variantes guiadas; Ataque Especial; Arena; dano entre escalas; condições; JSON e PDF; validação sem cortes; janela compacta.');
}catch(e){if(page)await page.screenshot({path:path.join(out,'advanced-failure.png'),fullPage:true}).catch(()=>{});console.error(e);process.exitCode=1}finally{if(app)await app.close()}})();
