const {test}=require('node:test');const assert=require('node:assert/strict');const R=require('../app/engine.js');
function item(name,cost,extra={}){return {id:R.uid(),name,cost,quantity:1,category:'vantagem',currency:'pontos',...extra}}
test('R0 starts with one PV and PM; R2 gives ten',()=>{let c=R.create();assert.equal(R.calculate(c).pv,1);c.attrs.R=2;assert.equal(R.calculate(c).pv,10);assert.equal(R.calculate(c).pm,10)});
test('extra resources buy effective R+2 including R0',()=>{let c=R.create();c.items=[item('Pontos de Vida Extras',1),item('Pontos de Magia Extras',1,{quantity:2})];let s=R.calculate(c);assert.equal(s.pv,10);assert.equal(s.pm,20);assert.equal(s.spent,3);assert.equal(s.attrs.R,0)});
test('budget, disadvantage ceiling and permanent racial modifiers',()=>{let c=R.create();c.attrs={F:2,H:5,R:2,A:1,PdF:0};c.items=[item('Elfo',2,{category:'unica',effects:{H:1}}),item('Devotado',-2,{category:'desvantagem'})];let s=R.calculate(c);assert.equal(s.spent,10);assert.equal(s.attrs.H,6);assert.ok(s.warnings.some(w=>w.includes('limite sugerido é 5')));c.items.push(item('Limitação',-5,{category:'desvantagem'}));assert.ok(R.calculate(c).warnings.some(w=>w.includes('limite da campanha')))});
test('kit acquisition uses cumulative cost, not flat cost',()=>{let c=R.create();c.items=[1,2,3,4].map(n=>item('Kit '+n,999,{category:'kit'}));assert.equal(R.calculate(c).kitCost,6);assert.equal(R.calculate(c).spent,6)});
test('PE options do not use character points',()=>{let c=R.create();c.items=[item('Magia',1,{category:'magia',currency:'PE'})];assert.equal(R.calculate(c).spent,0)});
test('critical doubles the attack stat, never H or the entire total',()=>{let c=R.create();c.attrs={F:3,H:4,R:2,A:2,PdF:1};assert.equal(R.roll(c,'melee',0,()=>.99).total,16);assert.equal(R.roll(c,'ranged',0,()=>.99).total,12);assert.equal(R.roll(c,'defense',0,()=>.99).total,14);assert.equal(R.roll(c,'melee',0,()=>0).total,8)});
test('characteristic test always fails on 6, even with huge bonus',()=>{let c=R.create();c.attrs.H=5;assert.equal(R.roll(c,'H',10,()=>.99).success,false);assert.equal(R.roll(c,'H',0,()=>.2).success,true)});
test('current resources never exceed maxima or fall below zero',()=>{let c=R.create();c.attrs.R=2;c.currentPV=999;c.currentPM=-5;assert.equal(R.calculate(c).currentPV,10);assert.equal(R.calculate(c).currentPM,0)});
test('import produces independent characters and preserves inventory, journals and modifiers',()=>{let c=R.create('Áurea');c.attrs.R=3;c.items=[item('Elfo',2,{category:'unica',effects:{H:1},notes:'áéç',requirements:{R:2}})];c.modifiers.pv=2;c.inventory=[{id:'x',name:'Arco',quantity:2,weight:1.5,equipped:true,notes:'teste'}];c.journal=[{date:'hoje',text:'Uma aventura.'}];const [copy]=R.validateImport(R.pack([c]));assert.notEqual(copy.id,c.id);assert.equal(copy.name,c.name);assert.equal(copy.journal[0].text,c.journal[0].text);assert.equal(R.calculate(copy).pv,17);assert.equal(copy.inventory[0].weight,1.5);assert.equal(copy.items[0].requirements.R,2)});
test('hostile and malformed imports are rejected explicitly',()=>{assert.throws(()=>R.validateImport({version:9,characters:[]}));assert.throws(()=>R.validateImport({version:1,characters:[{}]}));const c=R.create();c.attrs.F=Infinity;assert.throws(()=>R.validateImport(R.pack([c])),/inteiro/);c.attrs.F=0;c.portrait='javascript:alert(1)';assert.throws(()=>R.validateImport(R.pack([c])),/Retrato inválido/);c.portrait='';c.items=[item('x',-Infinity)];assert.throws(()=>R.validateImport(R.pack([c])),/Custo/)});
test('skill training changes difficulty thresholds exactly as the basic manual',()=>{const c=R.create();c.attrs.H=4;assert.equal(R.skillTest(c,true,'Fácil').automatic,true);assert.equal(R.skillTest(c,false,'Difícil').impossible,true);assert.equal(R.skillTest(c,false,'Fácil',()=>.1).target,3);assert.equal(R.skillTest(c,false,'Média',()=>.1).target,1);assert.equal(R.skillTest(c,true,'Média',()=>.1).target,5);assert.equal(R.skillTest(c,true,'Difícil',()=>.1).target,2)});
test('death table groups 2–3 and 4–5',()=>{assert.equal(R.deathResult(2),R.deathResult(3));assert.equal(R.deathResult(4),R.deathResult(5));assert.match(R.deathResult(4),/2d turnos/);assert.equal(R.deathResult(6),'Morto.')});
test('near death excludes R0 and caps threshold at five',()=>{let c=R.create();assert.equal(R.calculate(c).nearDeath,false);c.attrs.R=8;c.currentPV=6;assert.equal(R.calculate(c).nearDeath,false);c.currentPV=5;assert.equal(R.calculate(c).nearDeath,true);c.currentPV=0;assert.equal(R.calculate(c).nearDeath,false)});
test('flat resource adjustments apply after the R0 minimum',()=>{const c=R.create();c.modifiers.pv=5;c.modifiers.pm=2;assert.equal(R.calculate(c).pv,6);assert.equal(R.calculate(c).pm,3)});
