require('./runtime.cjs');
const {_electron:electron}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const path=require('node:path'),fs=require('node:fs'),assert=require('node:assert/strict');
const root=path.resolve('.'),profile=path.join(root,'tmp/flow-profile'),out=path.join(root,'tmp/qa');fs.mkdirSync(out,{recursive:true});fs.rmSync(profile,{recursive:true,force:true});
const config={executablePath:require('./runtime.cjs').electronPath(),args:['--no-sandbox','--disable-gpu',path.join(root,'app'),'--user-data-dir='+profile],env:{...process.env,ELECTRON_DISABLE_SECURITY_WARNINGS:'true'}};
(async()=>{let app;try{
 app=await electron.launch(config);let page=await app.firstWindow();await page.waitForSelector('h1');const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.locator('[data-view="personagem"]').click();await page.locator('[data-field="name"]').fill('Aurora, Guardiã dos Portais');await page.locator('[data-field="concept"]').fill('Exploradora arcana de Arton');await page.locator('[data-field="player"]').fill('Teste');await page.locator('[data-field="story"]').fill('Uma guardiã que protege as passagens entre mundos.');await page.locator('[data-attr="F"]').fill('1');await page.locator('[data-attr="F"]').press('Tab');await page.locator('[data-attr="H"]').fill('3');await page.locator('[data-attr="H"]').press('Tab');await page.locator('[data-attr="R"]').fill('2');await page.locator('[data-attr="R"]').press('Tab');
 assert.equal(await page.evaluate(()=>ch().concept),'Exploradora arcana de Arton');
 await page.locator('[data-view="poderes"]').click();await page.locator('[data-action="catalog"]').first().click();await page.locator('#catalog-search').fill('Pontos de Vida Extras');await page.waitForTimeout(400);await page.locator('[data-action="add-entry"]').first().click();await page.locator('#item-confirm').check();await page.locator('[data-action="save-item"]').click();assert.equal(await page.evaluate(()=>R.calculate(ch()).pv),20);
 await page.locator('#catalog-search').fill('Aceleração');await page.waitForTimeout(400);await page.screenshot({path:path.join(out,'catalogo.png'),fullPage:true});
 await page.locator('[data-view="inventario"]').click();await page.locator('[data-action="add-equipment"]').first().click();await page.locator('#eq-name').fill('Espada de prata');await page.locator('#eq-weight').fill('1.5');await page.locator('#eq-equipped').check();await page.locator('#eq-notes').fill('Relíquia da família.');await page.locator('[data-action="save-equipment"]').click();assert.equal(await page.evaluate(()=>ch().inventory[0].weight),1.5);
 await page.locator('[data-view="sessao"]').click();await page.locator('#resource-amount').fill('4');await page.locator('[data-action="damage"]').click();assert.equal(await page.evaluate(()=>R.calculate(ch()).currentPV),16);await page.locator('#xp-amount').fill('12');await page.locator('[data-action="gain-xp"]').click();await page.locator('[data-action="convert-xp"]').click();assert.equal(await page.evaluate(()=>ch().xp),2);assert.equal(await page.evaluate(()=>ch().earnedPoints),1);
 await page.locator('#journal-text').fill('Encontramos a chave do portal.');await page.locator('[data-action="journal"]').click();await page.locator('[data-action="roll"]').click();assert.ok(await page.locator('#last-roll').innerText());
 await page.locator('[data-view="magias"]').click();await page.locator('[data-action="custom"]').click();await page.locator('#item-name').fill('Luz de teste');await page.locator('#item-confirm').check();await page.locator('[data-action="save-item"]').click();await page.locator('[data-action="cast"]').click();await page.locator('#cast-cost').fill('3');await page.locator('[data-action="confirm-cast"]').click();assert.equal(await page.evaluate(()=>R.calculate(ch()).currentPM),7);
 // Test native dialog flow without interacting with the user's files.
 await app.evaluate(({dialog},p)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:p})},path.join(out,'aurora.3det.json'));
 await page.locator('[data-action="export"]').click();await page.waitForTimeout(500);let exported=JSON.parse(fs.readFileSync(path.join(out,'aurora.3det.json'),'utf8'));assert.equal(exported.characters[0].inventory[0].name,'Espada de prata');
 await app.evaluate(({dialog},p)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[p]})},path.join(out,'aurora.3det.json'));await page.locator('[data-action="import"]').first().click();await page.waitForTimeout(400);assert.equal(await page.evaluate(()=>state.characters.length),2);assert.ok((await page.evaluate(()=>ch().name)).includes('importado'));assert.equal(await page.evaluate(()=>ch().journal[0].text),'Encontramos a chave do portal.');
 await app.evaluate(({dialog},p)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:p})},path.join(out,'ficha.pdf'));await page.locator('[data-action="pdf"]').click();await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('PDF salvo'));assert.ok(fs.statSync(path.join(out,'ficha.pdf')).size>5000);
 await page.locator('[data-view="biblioteca"]').click();await page.locator('#library-search').fill('Aceleração');await page.waitForTimeout(400);await page.locator('[data-action="read-page"]').first().click();assert.ok(await page.locator('.page-text').innerText());await page.locator('[data-action="close"]').click();
 const opened=app.waitForEvent('window');await page.locator('[data-action="source"]').first().click();const pdf=await opened;await pdf.waitForLoadState('domcontentloaded');assert.ok(pdf.url().includes('.pdf'));await pdf.close();
 await page.locator('[data-view="resumo"]').click();await page.waitForTimeout(5000);await page.screenshot({path:path.join(out,'visao-geral.png'),fullPage:true});
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(960,720));await page.waitForTimeout(200);await page.screenshot({path:path.join(out,'compacto.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.locator('[data-view="personagem"]').click();await page.locator('[data-field="notes"]').fill('Persistência ao fechar imediatamente.');await page.evaluate(()=>flushSave());await app.close();app=null;
 app=await electron.launch(config);page=await app.firstWindow();await page.waitForSelector('h1');assert.equal(await page.evaluate(()=>state.characters.length),2);assert.equal(await page.evaluate(()=>ch().notes),'Persistência ao fechar imediatamente.');assert.equal(await page.evaluate(()=>R.calculate(ch()).currentPV),16);assert.equal(await page.evaluate(()=>R.calculate(ch()).currentPM),7);assert.equal(await page.evaluate(()=>ch().xp),2);
 assert.deepEqual(errors,[]);await app.close();app=null;console.log('PASS: edição, catálogo, PV/PM, inventário, XP, magia, diário, rolagem, exportação JSON, importação, PDF, pesquisa, leitura PDF, janela compacta e persistência.');
}catch(e){console.error(e);process.exitCode=1}finally{if(app)await app.close()}})();
