require('./runtime.cjs');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const {spawn}=require('node:child_process'),path=require('node:path'),fs=require('node:fs'),assert=require('node:assert/strict');
const root=path.resolve('.'),prefix=path.join(root,'tmp/wine-forja'),testDir=path.join(root,'tmp/windows-test');
fs.mkdirSync(prefix,{recursive:true});fs.rmSync(testDir,{recursive:true,force:true});fs.cpSync(path.join(root,'dist/Forja-3DeT-'+JSON.parse(fs.readFileSync(path.join(root,'app/package.json'),'utf8')).version+'-Windows-x64'),testDir,{recursive:true});
const log=fs.openSync(path.join(root,'tmp/windows-test.log'),'w');const env={...process.env,WINEPREFIX:prefix,WINEDEBUG:'-all',WINEDLLOVERRIDES:'mscoree,mshtml='};
(async()=>{let proc,browser;try{
 console.log('Preparando ambiente isolado de compatibilidade Windows…');
 proc=spawn('wine',[path.join(testDir,'Forja-3DeT.exe'),'--no-sandbox','--disable-gpu','--remote-debugging-port=9333'],{env,stdio:['ignore',log,log]});
 let ready=false;for(let n=0;n<90;n++){try{const r=await fetch('http://127.0.0.1:9333/json/version');if(r.ok){ready=true;break}}catch{}await new Promise(r=>setTimeout(r,1000));if(n===40)console.log('Aguardando a primeira inicialização do runtime Windows…')}
 if(!ready)throw Error('Runtime Windows não disponibilizou a interface de teste. Consulte tmp/windows-test.log.');
 browser=await chromium.connectOverCDP('http://127.0.0.1:9333');const context=browser.contexts()[0];let page=context.pages()[0];await page.waitForSelector('h1',{timeout:30000});assert.ok((await page.title()).includes('Forja'));await page.locator('[data-view="personagem"]').click();await page.locator('[data-field="name"]').fill('Teste Windows portátil');await page.locator('[data-view="resumo"]').click();await page.waitForTimeout(1500);await page.locator('[data-view="biblioteca"]').click();await page.locator('#library-search').fill('Aceleração');await page.waitForFunction(()=>document.querySelector('.panel-head h2')?.textContent.includes('páginas encontradas'));await page.locator('[data-view="ajustes"]').click();await page.locator('[data-field="modifiers.F"]').fill('20000');await page.locator('[data-field="modifiers.F"]').press('Tab');await page.locator('[data-view="modificadores"]').click();await page.locator('[data-action="new-bonus"]').first().click();await page.locator('#bonus-name').fill('Bônus no Windows');await page.locator('#bonus-value').fill('50000');await page.locator('[data-action="save-bonus"]').click();await page.evaluate(()=>flushSave());await page.reload();await page.waitForSelector('h1');assert.equal(await page.evaluate(()=>ch().modifiers.F),20000);assert.equal(await page.evaluate(()=>ch().bonuses[0].value),50000);await page.locator('.topbar [data-action="undo"]').click();assert.equal(await page.evaluate(()=>ch().bonuses.length),0);await page.locator('.topbar [data-action="redo"]').click();assert.equal(await page.evaluate(()=>ch().bonuses[0].value),50000);await page.evaluate(()=>flushSave());await page.locator('[data-view="modificadores"]').click();await page.screenshot({path:path.join(root,'tmp/qa/windows.png'),fullPage:true});assert.ok(fs.existsSync(path.join(testDir,'dados/fichas.json')));let data=JSON.parse(fs.readFileSync(path.join(testDir,'dados/fichas.json'),'utf8'));assert.equal(data.characters[0].name,'Teste Windows portátil');assert.equal(data.version,2);assert.equal(data.characters[0].modifiers.F,20000);assert.equal(data.characters[0].bonuses[0].value,50000);console.log('PASS: executável Windows abriu, renderizou a interface, pesquisou os livros, preservou valores de 20/50 mil após recarregar, desfez/refez e salvou em dados/fichas.json sob Wine.');
}catch(e){console.error(e.message);process.exitCode=1}finally{if(browser)await browser.close();if(proc)proc.kill('SIGTERM');spawn('wineserver',['-k'],{env,stdio:'ignore'});fs.closeSync(log)}})();
