'use strict';
const effectNames={...names,pv:'PV máximos',pm:'PM máximos',fa:'Ambos os ataques',melee:'Ataque corporal',ranged:'Ataque à distância',fd:'Defesa',initiative:'Iniciativa',dodge:'Esquiva',testF:'Teste de Força',testH:'Teste de Habilidade',testR:'Teste de Resistência',testA:'Teste de Armadura',testPdF:'Teste de Poder de Fogo'};
function choiceText(i){const labels={version:'Versão',senses:'Sentidos',attack:'Característica',level:'Nível',specials:'Variantes',detail:'Escolha',element:'Elemento'};return Object.entries(i.choices||{}).filter(([,v])=>v).map(([k,v])=>`${labels[k]||k}: ${v.replaceAll(',',', ')}`).join(' · ')}
const senseNames=['Audição Aguçada','Faro Aguçado','Infravisão','Radar','Ver o Invisível','Visão Aguçada','Visão de Raio X'];
function updateHistoryButtons(){for(const el of document.querySelectorAll('[data-action=undo]'))el.disabled=!editHistory.undo.length;for(const el of document.querySelectorAll('[data-action=redo]'))el.disabled=!editHistory.redo.length}
const editHistory=new EditHistory.Journal();let editLabel='Alterar ficha',historyReady=false;
const nfmt=n=>Number(n).toLocaleString('pt-BR',{maximumFractionDigits:8});
function formula(parts){return parts.map(p=>`${esc(p.label)} <b>${p.value>=0?'+':''}${nfmt(p.value)}</b>`).join(' <span class="muted">·</span> ')}
function calculationPanel(c,s){return `<section class="panel section-gap"><div class="panel-head"><h2>De onde vêm os números</h2>${btn('go-bonuses','Gerenciar modificadores →','ghost small')}</div><div class="formula-list">${[['fa','Ataque corporal',s.fa],['far','Ataque à distância',s.far],['fd','Defesa',s.fd],['initiative','Iniciativa',s.initiative],['dodge','Esquiva (antes do atacante)',s.dodge],['pv','PV máximos',s.pv],['pm','PM máximos',s.pm]].map(([k,name,value])=>`<details><summary>${name}: <strong>${nfmt(value)}${['fa','far','initiative'].includes(k)||k==='fd'&&!s.helpless?' + 1d':''}</strong></summary><p>${formula(s.breakdown[k])}</p>${['pv','pm'].includes(k)?'<small>O total tem mínimo de 1.</small>':''}</details>`).join('')}</div><p class="hint">Valores na escala ${esc(c.scale)}. Equivalência dos PV máximos em Ningen: ${nfmt(s.pv*s.scaleFactor)}. A conversão de dano usa a diferença de escala; não multiplique o dano novamente.</p></section>`}
function guidePanel(c,s){const done=[!!c.name&&c.name!=='Meu primeiro herói',R.attrs.some(k=>c.attrs[k]>0),c.items.length>0,s.warnings.length===0];return `<section class="panel section-gap"><div class="panel-head"><h2>Criação guiada</h2><span class="chip green">${done.filter(Boolean).length}/4 ETAPAS</span></div><div class="guide-steps">${[['Identidade e conceito','personagem'],['Pontuação e características','ajustes'],['Vantagens, perícias e escolhas','poderes'],['Conferência da ficha','resumo']].map(([label,v],n)=>`<button data-action="guide-step" data-goto="${v}" class="ghost">${done[n]?'✓':n+1+'.'} ${label}</button>`).join('')}</div><p class="hint">Escolha o perfil da campanha, distribua pontos e revise os avisos. Regras narrativas continuam sob decisão do mestre.</p></section>`}
function bonusView(c){return heading('Modificadores sob controle.','Cada bônus tem uma origem, um destino e um prazo.',btn('new-bonus','+ Novo modificador','primary'))+`<div class="actions section-gap">${btn('next-round','Avançar rodada','small')}${btn('end-combat','Encerrar combate','small')}</div><p class="hint">Modificadores de rodada expiram ao avançar; os de combate são desativados ao encerrar. Bônus permanentes ficam ativos até você desligá-los.</p><div class="list section-gap">${(c.bonuses||[]).map(b=>`<article class="list-item"><div><h3>${esc(b.name)} <span class="chip ${b.enabled?'green':''}">${b.enabled?'ATIVO':'INATIVO'}</span></h3><p><strong>${b.value>=0?'+':''}${nfmt(b.value)}</strong> em ${effectNames[b.target]} · ${b.duration==='rounds'?b.remaining+' rodada(s)':b.duration==='combat'?'até o fim do combate':'permanente'}</p><small>${esc(b.notes)}</small></div><div class="actions">${btn('toggle-bonus',b.enabled?'Desativar':'Ativar','small',`data-id="${b.id}"`)}${btn('edit-bonus','Editar','small',`data-id="${b.id}"`)}${btn('delete-bonus','Remover','danger ghost small',`data-id="${b.id}"`)}</div></article>`).join('')||empty('Registre arma +3, magia +10 ou condição −2 e veja o efeito nos cálculos.','new-bonus','Adicionar modificador')}</div>${calculationPanel(c,R.calculate(c))}`}
function bonusEditor(b=null){window.editingBonus=b;openModal(b?'Editar modificador':'Novo modificador',`<div class="field-grid"><div><label for="bonus-name">Origem / nome</label><input id="bonus-name" value="${esc(b?.name||'')}" placeholder="Ex.: bênção, arma, transformação"></div><div><label for="bonus-target">Aplica-se a</label><select id="bonus-target">${opts(Object.entries(effectNames),b?.target||'melee')}</select></div><div><label for="bonus-value">Valor positivo ou negativo</label><input id="bonus-value" type="number" step="any" value="${b?.value??0}"></div><div><label for="bonus-duration">Duração</label><select id="bonus-duration">${opts([['permanent','Permanente'],['combat','Até o fim do combate'],['rounds','Número de rodadas']],b?.duration||'permanent')}</select></div><div><label for="bonus-rounds">Rodadas (se aplicável)</label><input id="bonus-rounds" type="number" min="1" value="${b?.remaining||1}"></div><label class="toggle-label"><input id="bonus-enabled" type="checkbox" ${b?.enabled!==false?'checked':''}>Ativo</label></div><div class="section-gap"><label for="bonus-notes">Condição de uso / referência</label><textarea id="bonus-notes">${esc(b?.notes||'')}</textarea></div><p class="hint">Bônus de característica alteram suas parcelas nos críticos. Bônus diretos de ataque ou defesa são somados ao total. Valores válidos não são reduzidos ao salvar.</p>`,btn('close','Cancelar','ghost')+btn('save-bonus','Salvar modificador','primary'))}
function historyView(){return heading('Cada alteração pode voltar.','Histórico local com até 30 alterações recentes e até 10 MB de dados.',`<div class="actions">${btn('undo','↶ Desfazer','small',editHistory.undo.length?'':'disabled')}${btn('redo','↷ Refazer','small',editHistory.redo.length?'':'disabled')}</div>`)+`<div class="panel"><div class="list">${editHistory.undo.slice().reverse().map((e,n)=>`<div class="list-item"><div><h3>${esc(e.label)}</h3><small>${new Date(e.time).toLocaleString('pt-BR')} · ${e.changes.length} campo(s) / operação(ões)</small><p>${e.changes.slice(0,8).map(p=>esc(p.kind==='field'?({attrs:'Características',items:'Vantagens e poderes',bonuses:'Modificadores',modifiers:'Ajustes',combat:'Contexto do combate',conditions:'Condições',currentPV:'PV',currentPM:'PM',history:'Registro da mesa',inventory:'Equipamentos',notes:'Anotações',name:'Nome',xp:'Experiência',journal:'Diário',cash:'Dinheiro',ruleMode:'Modo de regras',budget:'Orçamento',earnedPoints:'Pontos de evolução'}[p.key]||p.key):p.kind==='add'?'Personagem criado':'Personagem removido')).join(', ')}</p></div>${n===0?btn('undo','Desfazer esta alteração','small'):''}</div>`).join('')||empty('As próximas edições aparecerão aqui.')}</div><p class="hint">Desfazer e refazer funcionam em ordem. Uma nova edição após desfazer inicia uma nova sequência. O histórico local permanece ao reabrir; os arquivos de ficha compartilham o estado atual.</p></div>`}
function combatPanel(c){return `<section class="panel section-gap"><h2>Contexto do combate</h2><div class="field-grid">${select('Escala do oponente','combat.opponentScale',R.scales,c.combat.opponentScale)}${field('Habilidade do atacante (para esquiva)','combat.opponentH',c.combat.opponentH,'number')}${select('Sua Armadura contra este ataque','combat.armorMode',[['normal','Normal'],['extra','Armadura Extra: A × 2'],['vulneravel','Vulnerabilidade: A = 0']],c.combat.armorMode)}${select('Invulnerabilidade contra este ataque','combat.invulnerable',[['false','Não'],['true','Sim: FA recebida ÷ 10']],String(c.combat.invulnerable))}${select('Comparar escalas em testes de F/R','combat.scaleTests',[['false','Não'],['true','Sim, usar a escala do oponente']],String(c.combat.scaleTests))}</div><p class="hint">Defesa usa o contexto acima. Indefeso, Paralisado ou Inconsciente retiram H e dado da FD e impedem esquiva. No crítico, Armadura Extra resulta em A × 3. Invulnerabilidade reduz a FA recebida antes da comparação.</p><div class="divider"></div><h3>Calculadora de dano entre escalas</h3><div class="field-grid"><div><label for="damage-fa">FA do ataque (total da rolagem)</label><input id="damage-fa" type="number" value="0"></div><div><label for="damage-fd">FD do alvo (total da defesa)</label><input id="damage-fd" type="number" value="0"></div><div><label for="damage-direction">Direção</label><select id="damage-direction">${opts([['incoming','Oponente ataca este personagem'],['outgoing','Este personagem ataca o oponente']],'incoming')}</select></div><label class="toggle-label"><input id="damage-invul" type="checkbox">O alvo externo tem Invulnerabilidade</label></div><div class="actions section-gap">${btn('calculate-damage','Calcular dano','primary')}${btn('apply-damage','Aplicar aos meus PV','small','disabled')}</div><div id="damage-result" role="status" class="section-gap"></div><p class="hint">Use FA e FD nas escalas próprias, antes da conversão. Para dano recebido, a Invulnerabilidade é a do contexto acima. Dano externo é apenas informado. Fonte: básico, PDF p. 128; combate, PDF p. 71–72.</p></section>`}
function readNumber(id,label,min=-R.MAX,integer=false){return R.number($(id).value,label,min,R.MAX,integer)}
Object.assign(actions,{
 'guide-step':el=>{view=el.dataset.goto;render();window.scrollTo(0,0)},
 'go-bonuses':()=>{view='modificadores';render()},'new-bonus':()=>bonusEditor(),'edit-bonus':el=>bonusEditor(ch().bonuses.find(b=>b.id===el.dataset.id)),
 'save-bonus':()=>{const name=$('#bonus-name').value.trim();if(!name)throw Error('Informe a origem do modificador.');const bonus={id:window.editingBonus?.id||R.uid(),name,target:$('#bonus-target').value,value:readNumber('#bonus-value','Modificador'),duration:$('#bonus-duration').value,remaining:readNumber('#bonus-rounds','Rodadas',1,true),enabled:$('#bonus-enabled').checked,notes:$('#bonus-notes').value};const copy=structuredClone(ch());const index=copy.bonuses.findIndex(b=>b.id===bonus.id);if(index<0)copy.bonuses.push(bonus);else copy.bonuses[index]=bonus;R.calculate(copy);ch().bonuses=copy.bonuses;save();closeModal();render()},
 'toggle-bonus':el=>{const b=ch().bonuses.find(b=>b.id===el.dataset.id);if(!b.enabled&&b.duration==='rounds'&&b.remaining===0)throw Error('Este efeito expirou. Edite o número de rodadas para reativá-lo.');b.enabled=!b.enabled;save();render()},
 'delete-bonus':el=>{window.deletingBonus=el.dataset.id;confirmAction('Remover modificador?','O bônus será removido. Você poderá recuperar pelo histórico.','confirm-delete-bonus')},
 'confirm-delete-bonus':()=>{ch().bonuses=ch().bonuses.filter(b=>b.id!==window.deletingBonus);save();closeModal();render()},
 'next-round':()=>{const expired=R.advanceRound(ch());log('Rodada avançada.'+(expired.length?' Expiraram: '+expired.join(', '):''));render()},
 'end-combat':()=>{R.endCombat(ch());log('Combate encerrado; modificadores com duração de combate foram desativados.');render()},
 undo:()=>applyHistory('undo'),redo:()=>applyHistory('redo'),
 'calculate-damage':()=>{const direction=$('#damage-direction').value,c=ch();const result=R.damage(readNumber('#damage-fa','FA'),readNumber('#damage-fd','FD'),direction==='incoming'?c.combat.opponentScale:c.scale,direction==='incoming'?c.scale:c.combat.opponentScale,direction==='incoming'?c.combat.invulnerable:$('#damage-invul').checked);window.pendingDamage={...result,direction,characterId:c.id,applied:false};$('#damage-result').innerHTML=`<strong class="dice-result">${nfmt(result.value)} PV</strong><p>${esc(result.explanation)}</p>`;$('#app [data-action="apply-damage"]').disabled=direction!=='incoming'},
 'apply-damage':()=>{const pending=window.pendingDamage;if(!pending||pending.applied||pending.direction!=='incoming'||pending.characterId!==ch().id)throw Error('Calcule novamente o dano recebido.');ch().currentPV=Math.max(0,R.calculate(ch()).currentPV-pending.value);if(pending.value>0)ch().conditions=ch().conditions.filter(x=>x!=='Paralisado');pending.applied=true;log(`Recebeu ${pending.value} PV de dano. ${pending.explanation}`);render()},
 'activate-item':el=>{const i=ch().items.find(i=>i.id===el.dataset.id);if(i.name==='Arena'){const name='Arena: '+(i.choices?.detail||'terreno escolhido');const prior=ch().bonuses.find(b=>b.name===name&&b.target==='H');if(prior){prior.enabled=true;save();render();return}ch().bonuses.push({id:R.uid(),name:'Arena: '+(i.choices?.detail||'terreno escolhido'),target:'H',value:2,duration:'combat',remaining:0,enabled:true,notes:'Ative somente dentro da arena.'});save();render();toast('Arena ativada. Desative ao sair do terreno.')}else if(i.name==='Ataque Especial')useSpecialAttack(i)}
});
function applyHistory(direction){const label=editHistory.apply(state,direction,chars=>R.validateImport(R.pack(chars),{preserveIds:true}));if(!label)return;editHistory.suspended=true;try{save()}finally{editHistory.suspended=false}closeModal();render();toast(`${direction==='undo'?'Desfeito':'Refeito'}: ${label}`)}
function useSpecialAttack(i){const flags=(i.choices?.specials||'').split(',').filter(Boolean),s=R.calculate(ch());if(flags.includes('Perto da Morte')&&!s.nearDeath)throw Error('Este ataque exige estar Perto da Morte.');const level=R.number(i.choices?.level||1,'Nível do Ataque Especial',1,10,true);const cost=Math.max(1,level+flags.reduce((sum,f)=>sum+({'Amplo':2,'Penetrante':1,'Perigoso':2,'Poderoso':2,'Perto da Morte':-1}[f]||0),0));if(flags.includes('Paralisante'))throw Error('Variante Paralisante: use o custo e o teste de Paralisia na fonte. A rolagem automática deste ataque não aplica essa variante.');if(s.currentPM<cost)throw Error('PM insuficientes para o ataque.');const c=structuredClone(ch()),key=i.choices?.attack==='PdF'?'PdF':'F';c.bonuses.push({id:R.uid(),name:i.name,target:key,value:level*2,enabled:true,duration:'permanent'});const result=R.roll(c,key==='F'?'melee':'ranged',0,Math.random,{criticalAt:flags.includes('Perigoso')?5:6,criticalExtra:flags.includes('Poderoso')?2:1});if(result.blocked)throw Error(result.explanation);ch().currentPM=s.currentPM-cost;const note=flags.map(f=>({'Penetrante':'Alvo: A−1 na FD.','Preciso':'Alvo: H−1 na FD.','Lento':'Alvo: H+2 na esquiva.','Teleguiado':'Alvo: H−1 na esquiva.','Amplo':'Ataque em área: inclua aliados e aplique as esquivas.'}[f]||'')).filter(Boolean).join(' ');log(`${i.name}: ${result.explanation} Custo: ${cost} PM. ${note}`);render();openModal('Ataque Especial',`<div class="dice-result">FA ${nfmt(result.total)}</div><p>${esc(result.explanation)}</p><p>${esc(note)}</p><p>${cost} PM gastos.</p>`)}
const originalSummary=summary,originalCharacter=character,originalSettings=settings,originalSession=session,originalPrint=printHTML;
summary=(c,s)=>originalSummary(c,s)+guidePanel(c,s)+calculationPanel(c,s);
character=(c,s)=>originalCharacter(c,s)+guidePanel(c,s);
settings=(c,s)=>`<section class="panel" style="margin-bottom:24px"><h2>Liberdade e limites da campanha</h2><div class="field-grid">${select('Modo de regras','ruleMode',[['standard','Padrão: avisar sobre limites'],['free','Livre: sem avisos de limite inicial']],c.ruleMode)}${field('Limite sugerido de característica na criação','attributeLimit',c.attributeLimit,'number')}</div><p class="hint">Limites da campanha geram avisos; nunca reduzem valores. Se um valor ou resultado for grande demais para um cálculo confiável, a alteração será recusada com uma mensagem. Alterações anteriores já cortadas pela versão antiga precisam ser recuperadas de uma cópia original.</p></section>`+originalSettings(c,s);
session=(c,s)=>originalSession(c,s)+combatPanel(c)+calculationPanel(c,s)+`<div class="actions section-gap">${btn('next-round','Avançar rodada','small')}${btn('end-combat','Encerrar combate','small')}${btn('go-bonuses','Ver efeitos ativos','small')}</div>`;
printHTML=c=>{const s=R.calculate(c);return originalPrint(c).replace('<div class="footer">',`<h2>Modificadores registrados</h2>${(c.bonuses||[]).map(b=>`<p><b>${esc(b.name)}</b>: ${b.value>=0?'+':''}${nfmt(b.value)} em ${effectNames[b.target]} · ${b.enabled?'ativo':'inativo'} · ${b.duration==='rounds'?b.remaining+' rodadas':b.duration==='combat'?'até o fim do combate':'permanente'}. ${esc(b.notes)}</p>`).join('')||'<p>Nenhum.</p>'}<h2>Memória dos cálculos</h2>${[['fa','FA corporal'],['far','FA à distância'],['fd','FD'],['initiative','Iniciativa']].map(([k,label])=>`<p><b>${label}</b>: ${s.breakdown[k].map(x=>esc(x.label)+' ('+nfmt(x.value)+')').join(' + ')} = ${nfmt(s[k])}${k==='fd'&&s.helpless?' (indefeso, sem dado)':' + 1d'}</p>`).join('')}<p>Escala: ${esc(c.scale)}. PV e características na própria escala. Contexto de defesa: ${esc(c.combat.armorMode)}.</p><div class="footer">`)};
nav.splice(4,0,['modificadores','±','Modificadores']);nav.push(['historico','↶','Histórico de edições']);
const basicGuide=e=>e?.book==='3d&tManualbasico'?BASIC_GUIDE[e.name]:null;
function reviewedEntry(e){if(!e)return e;const g=basicGuide(e);return g?{...e,cost:g.cost,costs:g.costs,text:g.summary||e.text,requiredItems:g.requiredItems||[],effects:g.effects||{},costReviewed:true,guideReviewed:!!g.guideReviewed}:e}
const originalEntryDetails=entryDetails,originalItemEditor=itemEditor;
entryDetails=e=>{window.modalEntry=e;originalEntryDetails(reviewedEntry(e))};
itemEditor=(entry=null,existing=null)=>{window.editingGuide=null;entry=reviewedEntry(entry);originalItemEditor(entry,existing);const i=window.editingItem.item,g=basicGuide(existing||entry);if(!existing&&entry){i.requiredItems=entry.requiredItems||[];for(const [k,v] of Object.entries(entry.effects||{})){i.effects[k]=v;const input=$('#effect-'+k);if(input)input.value=v}}
 if(!g)return;
 const extra=document.createElement('section');extra.className='guide-editor panel section-gap';extra.innerHTML=`<h3>Escolhas guiadas · Manual básico</h3><p class="hint">${g.guideReviewed?'Resumo e escolhas revisados.':'Título e custo conferidos; consulte o texto original para efeitos e exceções.'} Custos previstos: ${g.costs.join(', ')} ponto(s). O mestre pode ajustar o custo no campo principal.</p>${(g.choices||[]).map(choice=>`<div class="section-gap"><label for="choice-${choice.key}">${esc(choice.label)}</label>${choice.values.length?`<select id="choice-${choice.key}" data-choice="${choice.key}">${opts(choice.values,i.choices?.[choice.key]||'')}</select>`:`<input id="choice-${choice.key}" data-choice="${choice.key}" value="${esc(i.choices?.[choice.key]||'')}">`}</div>`).join('')}${g.specialAttack?`<div class="section-gap"><label for="choice-level">Nível do ataque (acima de I exige evolução)</label><select id="choice-level" data-choice="level">${opts(Array.from({length:10},(_,n)=>[String(n+1),`Nível ${n+1}: +${2*(n+1)} na característica`]),i.choices?.level||'1')}</select></div><div class="section-gap"><label>Variantes do Ataque Especial</label><div class="field-grid">${Object.keys(specialCosts).map(f=>`<label class="toggle-label"><input type="checkbox" data-special="${f}" ${(i.choices?.specials||'').split(',').includes(f)?'checked':''}>${f} (${specialCosts[f]>=0?'+':''}${specialCosts[f]})</label>`).join('')}</div><p id="special-preview" class="hint"></p></div>`:''}${g.requiredItems?.length?`<p class="hint">Requer: ${g.requiredItems.map(esc).join(', ')}.</p>`:''}`;
 $('#modal .modal-actions').before(extra);window.editingGuide=g;if(g.specialAttack)updateSpecialPreview(false);
 if(i.name==='Sentidos Especiais'){const input=$('#choice-senses');input.type='hidden';const options=document.createElement('div');options.className='field-grid';options.innerHTML=senseNames.map(name=>`<label class="toggle-label"><input type="checkbox" data-sense="${name}" ${(i.choices?.senses||'').split(',').map(x=>R.normalize(x.trim())).includes(R.normalize(name))?'checked':''}>${name}</label>`).join('');input.after(options);syncSenses()}

};
const specialCosts={'Amplo':2,'Lento':-1,'Paralisante':1,'Penetrante':1,'Perigoso':2,'Perto da Morte':-2,'Poderoso':2,'Preciso':1,'Teleguiado':1};
function syncSenses(){const all=$('#choice-version')?.value.startsWith('Todos');for(const el of document.querySelectorAll('[data-sense]')){el.disabled=!!all;if(all)el.checked=true}$('#choice-senses').value=Array.from(document.querySelectorAll('[data-sense]:checked')).map(el=>el.dataset.sense).join(', ')}
function updateSpecialPreview(updateCost=true){const flags=Array.from(document.querySelectorAll('[data-special]:checked')).map(el=>el.dataset.special);const level=Number($('#choice-level')?.value||1);const points=Math.max(1,level+flags.reduce((sum,f)=>sum+specialCosts[f],0));if(updateCost)$('#item-cost').value=points;$('#special-preview').textContent=`Custo calculado: ${points} ponto(s). Variantes Amplo, Lento e Teleguiado exigem PdF. Os modificadores de defesa/esquiva do alvo são informados na rolagem para aplicação pelo mestre.`}
const originalSaveItem=actions['save-item'];actions['save-item']=()=>{const i=window.editingItem.item;const choices=Object.fromEntries(Array.from(document.querySelectorAll('[data-choice]')).map(el=>[el.dataset.choice,el.value.trim()]));if(window.editingGuide?.specialAttack&&$('#special-preview')){const flags=Array.from(document.querySelectorAll('[data-special]:checked')).map(el=>el.dataset.special);if(choices.attack==='F'&&flags.some(f=>['Amplo','Lento','Teleguiado'].includes(f)))throw Error('Amplo, Lento e Teleguiado só podem ser usados com PdF.');choices.specials=flags.join(',')}
 if(i.name==='Sentidos Especiais'){const allowed=senseNames;if(choices.version?.startsWith('Todos')){choices.senses=allowed.join(', ');$('#choice-senses').value=choices.senses}else{const senses=(choices.senses||'').split(',').map(s=>R.normalize(s.trim())).filter(Boolean);if(new Set(senses).size!==3||senses.length!==3||senses.some(s=>!allowed.some(a=>R.normalize(a)===s)))throw Error('Escolha três sentidos diferentes: '+allowed.join(', ')+'.')}}
 for(const el of document.querySelectorAll('[data-choice]'))if(!el.value.trim())throw Error('Preencha as escolhas guiadas antes de adicionar.');
 i.choices={...(i.choices||{}),...choices};originalSaveItem();window.editingGuide=null};
document.addEventListener('change',event=>{if(event.target.dataset.sense||event.target.dataset.choice==='version'&&$('#choice-senses'))syncSenses();if(event.target.dataset.special||event.target.dataset.choice==='level')updateSpecialPreview();if(event.target.dataset.choice==='version'){const index=event.target.selectedIndex;const costs=window.editingGuide?.costs;if(costs?.[index]!=null)$('#item-cost').value=costs[index]}});
const actionLabels={'save-bonus':'Salvar modificador','toggle-bonus':'Ativar / desativar modificador','confirm-delete-bonus':'Remover modificador','next-round':'Avançar rodada','end-combat':'Encerrar combate','save-item':'Editar opção da ficha','confirm-remove-item':'Remover opção da ficha','save-equipment':'Editar equipamento','confirm-remove-equipment':'Remover equipamento','create-character':'Criar personagem','confirm-delete-character':'Excluir personagem','duplicate':'Duplicar personagem','condition':'Alterar condição','roll':'Realizar rolagem','confirm-cast':'Conjurar magia','apply-damage':'Aplicar dano','activate-item':'Ativar poder'};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(b)editLabel=actionLabels[b.dataset.action]||b.textContent.trim()||'Alterar ficha'},true);
document.addEventListener('input',e=>{if(e.target.dataset.field||e.target.dataset.attr||e.target.dataset.resource)editLabel='Editar campo: '+(e.target.labels?.[0]?.textContent||e.target.getAttribute('aria-label')||e.target.dataset.field)},true);
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&!e.altKey&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)){if(e.key.toLowerCase()==='z'){e.preventDefault();applyHistory(e.shiftKey?'redo':'undo')}else if(e.key.toLowerCase()==='y'){e.preventDefault();applyHistory('redo')}}});
init();
