const {app,BrowserWindow,ipcMain,dialog,shell}=require('electron');
const fs=require('node:fs');const path=require('node:path');const {pathToFileURL}=require('node:url');
let main;
// An adjacent data folder makes the extracted Windows distribution portable.
if(process.platform==='win32'&&app.isPackaged){try{const data=path.join(path.dirname(process.execPath),'dados');fs.mkdirSync(data,{recursive:true});fs.accessSync(data,fs.constants.W_OK);app.setPath('userData',data)}catch{}}
app.setName('Forja 3D&T Alpha');
const gotLock=app.requestSingleInstanceLock();if(!gotLock)app.quit();app.on('second-instance',()=>{if(main){if(main.isMinimized())main.restore();main.focus()}});
function trusted(e){if(e.sender!==main?.webContents)throw Error('Origem inválida')}
const datafile=()=>path.join(app.getPath('userData'),'fichas.json');
const Store=require('./store.cjs');let store;const getStore=()=>store||(store=new Store(datafile()));
ipcMain.handle('load',e=>{trusted(e);return getStore().load()});
ipcMain.handle('save',(e,data)=>{trusted(e);return getStore().save(data)});
ipcMain.handle('export',async(e,{data,name})=>{trusted(e);const {canceled,filePath}=await dialog.showSaveDialog(main,{title:'Salvar ficha compartilhável',defaultPath:name.replace(/[<>:"/\\|?*]/g,'_')+'.3det.json',filters:[{name:'Ficha 3D&T',extensions:['json']}]});if(canceled)return false;fs.writeFileSync(filePath,JSON.stringify(data,null,2));return filePath});
ipcMain.handle('import',async e=>{trusted(e);const {canceled,filePaths}=await dialog.showOpenDialog(main,{title:'Importar ficha ou backup',filters:[{name:'Ficha 3D&T',extensions:['json']}],properties:['openFile']});if(canceled)return null;if(fs.statSync(filePaths[0]).size>100*1024*1024)throw Error('Arquivo muito grande.');return JSON.parse(fs.readFileSync(filePaths[0],'utf8'))});
ipcMain.handle('pdf',async(e,html)=>{trusted(e);const {canceled,filePath}=await dialog.showSaveDialog(main,{defaultPath:'Ficha-3DeT.pdf',filters:[{name:'PDF',extensions:['pdf']}]});if(canceled)return false;const w=new BrowserWindow({show:false,webPreferences:{sandbox:true,nodeIntegration:false,contextIsolation:true}});w.webContents.setWindowOpenHandler(()=>({action:'deny'}));try{await w.loadURL('data:text/html;charset=utf-8,'+encodeURIComponent(html));const buf=await w.webContents.printToPDF({printBackground:true,pageSize:'A4',margins:{top:0.4,bottom:0.4,left:0.4,right:0.4}});fs.writeFileSync(filePath,buf);return filePath}finally{w.destroy()}});
ipcMain.handle('source',async(e,{file,page})=>{trusted(e);const books=require('./data/books.json');if(!books.some(b=>b.file===file))throw Error('Livro desconhecido.');const f=path.join(__dirname,'livros',file);if(!fs.existsSync(f))throw Error('PDF não encontrado na pasta livros.');const w=new BrowserWindow({width:1150,height:850,title:'Biblioteca • Forja 3D&T',webPreferences:{sandbox:true,nodeIntegration:false,contextIsolation:true}});w.webContents.setWindowOpenHandler(()=>({action:'deny'}));w.webContents.on('will-navigate',(ev,url)=>{if(!url.startsWith(pathToFileURL(f).href))ev.preventDefault()});await w.loadURL(pathToFileURL(f).href+'#page='+Math.max(1,Number(page)||1));return true});
app.whenReady().then(()=>{main=new BrowserWindow({width:1440,height:960,minWidth:900,minHeight:640,backgroundColor:'#101820',title:'Forja 3D&T Alpha',autoHideMenuBar:true,webPreferences:{preload:path.join(__dirname,'preload.cjs'),nodeIntegration:false,contextIsolation:true,sandbox:true}});main.webContents.setWindowOpenHandler(()=>({action:'deny'}));main.webContents.on('will-navigate',e=>e.preventDefault());main.loadFile(path.join(__dirname,'index.html'));let closing=false;main.on('close',event=>{if(closing)return;event.preventDefault();main.webContents.executeJavaScript('typeof flushSave === \'function\' ? flushSave() : null').catch(()=>{}).finally(()=>{closing=true;main.close()})});});
app.on('window-all-closed',()=>app.quit());
